export const GET_USER_LIST = 'getUserList'
export const GET_ALL_USER = 'getAllUser'
export const GET_USERS_BY_USERNAME = 'getUsersByUsername'
export const ADD_USER = 'addUser'
export const DELETE_USER_BY_ID = 'deleteUserById'
